import Sidebar from "@/components/layout/Sidebar"
import "./globals.css"
import Layout from "@/components/layout/Layout"

export const metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <link
                    href="https://api.fontshare.com/v2/css?f[]=cabinet-grotesk@1,800,500,700,400,300,900&display=swap"
                    rel="stylesheet"
                ></link>
            </head>
            <body>
                <Sidebar />
                <Layout>{children}</Layout>
            </body>
        </html>
    )
}
